# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [2]:
import numpy as np

In [3]:
arr = np.arange(10)
arr2 = arr.reshape((2,5))
# in a single statement we can do it as arr2 = np.arange(10).reshape((2,5))
arr2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [4]:
arr1 = np.array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])
arr2 = np.array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])
np.vstack((arr1, arr2))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [5]:
# we can also use arrays from Question 2

a = np.arange(10).reshape((2,5))
b = np.ones(10).reshape((2,5)).astype(int)
np.hstack((a, b))

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [6]:
arr = np.arange(10).reshape((2,5,1)) # we can use 2D array as well: arr = np.arange(10).reshape((2,5))
# print(arr)
arr.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [7]:
arr1 = np.arange(15).reshape((3,5))
# print(arr1)
arr1.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [8]:
arr2 = np.arange(15)
arr2.reshape((5,3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

## Question:7

### Create 5x5 an array and find the square of an array?

In [9]:
arr1 = np.arange(2,27).reshape((5,5))
print(arr1)
print(np.square(arr1))   # we can also compute square without square function as: arr1 = arr1 ** 2

[[ 2  3  4  5  6]
 [ 7  8  9 10 11]
 [12 13 14 15 16]
 [17 18 19 20 21]
 [22 23 24 25 26]]
[[  4   9  16  25  36]
 [ 49  64  81 100 121]
 [144 169 196 225 256]
 [289 324 361 400 441]
 [484 529 576 625 676]]


## Question:8

### Create 5x6 an array and find the mean?

In [21]:
arr_m = np.random.randn(5,6)
print(arr_m)
print(np.mean(arr_m))   # We can also use array instance method as: arr_m.mean()
print("Mean along axis 0: ",arr_m.mean(axis=0))
print("Mean along axis 1: ",arr_m.mean(axis=1))


[[-4.85351433e-01 -1.46850243e-04  1.42653630e+00  9.57236929e-01
   1.86296682e+00  6.45459227e-01]
 [-9.75359622e-01  1.88967368e-01 -4.18773321e-01 -4.98101546e-01
   1.38912906e-01  6.72853326e-01]
 [ 1.58927522e+00  4.34392865e-01  5.72904832e-01  2.30323724e-01
   1.43496937e+00 -1.50968010e+00]
 [ 9.66253430e-01 -7.37688665e-01 -1.43123601e+00  4.99776529e-01
  -9.22585304e-01  1.38469610e+00]
 [ 1.34107145e+00 -5.55114727e-01 -3.06910446e-01  1.02199603e+00
  -5.33017803e-01 -5.44659945e-01]]
0.21499888847684906
Mean along axis 0:  [ 0.48717781 -0.133918   -0.03149573  0.44224633  0.3962492   0.12973372]
Mean along axis 1:  [ 0.73445016 -0.14858348  0.45869765 -0.04013065  0.07056076]


## Question:9

### Find the standard deviation of the previous array in Q8?

In [22]:
print(np.std(arr_m))
arr_m.std()

0.9196851270158268


0.9196851270158268

## Question:10

### Find the median of the previous array in Q8?

In [23]:
np.median(arr_m)

0.20964554616846312

## Question:11

### Find the transpose of the previous array in Q8?

In [27]:
arr_m.T              # we can also find transpose as: arr_m.transpose()

array([[-4.85351433e-01, -9.75359622e-01,  1.58927522e+00,
         9.66253430e-01,  1.34107145e+00],
       [-1.46850243e-04,  1.88967368e-01,  4.34392865e-01,
        -7.37688665e-01, -5.55114727e-01],
       [ 1.42653630e+00, -4.18773321e-01,  5.72904832e-01,
        -1.43123601e+00, -3.06910446e-01],
       [ 9.57236929e-01, -4.98101546e-01,  2.30323724e-01,
         4.99776529e-01,  1.02199603e+00],
       [ 1.86296682e+00,  1.38912906e-01,  1.43496937e+00,
        -9.22585304e-01, -5.33017803e-01],
       [ 6.45459227e-01,  6.72853326e-01, -1.50968010e+00,
         1.38469610e+00, -5.44659945e-01]])

## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [31]:
arr = np.arange(1,17).reshape((4,4))
print(arr)
np.sum(np.diag(arr))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


34

## Question:13

### Find the determinant of the previous array in Q12?

In [32]:
from numpy.linalg import det

In [33]:
det(arr)

-1.820448242817726e-31

## Question:14

### Find the 5th and 95th percentile of an array?

In [41]:
arr = np.arange(1,11)
print("5th percentile: ", np.percentile(arr, 5))
print("95th percentile: ", np.percentile(arr, 95))

5th percentile:  1.4500000000000002
95th percentile:  9.549999999999999


## Question:15

### How to find if a given array has any null values?

In [53]:
arr = np.array([[4, 43, 101, 0, 13,np.nan, 40, 61], [3, np.nan, 4, 45, np.nan, 0, 43, np.nan]])
np.isnan(arr)  # True for null values

array([[False, False, False, False, False,  True, False, False],
       [False,  True, False, False,  True, False, False,  True]])