# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [31]:
import numpy as np

2. Create a null vector of size 10 

In [32]:
arr1 = np.zeros(10)
arr1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3. Create a vector with values ranging from 10 to 49

In [33]:
arr2 = np.arange(10,50)

4. Find the shape of previous array in question 3

In [34]:
arr2.shape

(40,)

5. Print the type of the previous array in question 3

In [35]:
arr2.dtype

dtype('int32')

6. Print the numpy version and the configuration


In [36]:
print(np.__version__)
print(np.show_config())

1.18.5
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/ProgramData/Anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\

7. Print the dimension of the array in question 3


In [37]:
arr2.ndim

1

8. Create a boolean array with all the True values

In [38]:
arr_bool = np.array([True, True, True, True])
arr_bool

array([ True,  True,  True,  True])

9. Create a two dimensional array




In [39]:
two_dim_arr = np.array([[1,2,3,4],[5,6,7,8]])
# another way of creating 2 Dimensional array:  two_dim_arr = np.arange(15).reshape(3,5)   
two_dim_arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

10. Create a three dimensional array



In [40]:
three_dim_arr = np.array([[[10,20,30,40],[50,60,70,80]],[[90,100,110,120],[130,140,150,160]]])
#another way of creating 3 Dimensional array:  three_dim_arr = np.arange(16).reshape(2,2,4) 
three_dim_arr

array([[[ 10,  20,  30,  40],
        [ 50,  60,  70,  80]],

       [[ 90, 100, 110, 120],
        [130, 140, 150, 160]]])

Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [41]:
arr1 = np.array([1,2,3,4])
reverse_arr =arr1[::-1]
reverse_arr

array([4, 3, 2, 1])

12. Create a null vector of size 10 but the fifth value which is 1 

In [42]:
arr1 = (np.arange(10) == 4).astype(int)
arr1

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

13. Create a 3x3 identity matrix

In [50]:
id_mtx = np.identity(3)
#another way is: id_mtx = np.eye(3)
id_mtx

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [51]:
arr = (np.array([1, 2, 3, 4, 5])).astype(float)
arr

array([1., 2., 3., 4., 5.])

15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [55]:
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]])  
arr2 = np.array([[0., 4., 1.],

           [7., 2., 12.]])
arr1 * arr2                   # or we can use multiplication function: np.multiply(arr1,arr2)

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [56]:
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]]) 
arr2 = np.array([[0., 4., 1.],

            [7., 2., 12.]])
arr3 = arr1 == arr2             # or we can also have an array by comparing less than or greater than too
arr3

array([[False, False, False],
       [False, False, False]])

17. Extract all odd numbers from arr with values(0-9)

In [19]:
arr = np.arange(10)
arr[arr%2 == 1]

array([1, 3, 5, 7, 9])

18. Replace all odd numbers to -1 from previous array

In [20]:
arr[arr%2 == 1] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [21]:
arr = np.arange(10)
arr[5:9] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

20. Create a 2d array with 1 on the border and 0 inside

In [57]:
arr = np.ones((5,5))
arr
arr[1:-1,1:-1] = 0
arr

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [58]:
arr2d = np.array([[1, 2, 3],

            [4, 5, 6], 

            [7, 8, 9]])
arr2d[1,1] = 12
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [62]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[0] = 64   # if we want to have value of 64 on first array of first depth then we can do as: arr3d[0,0] = 64
arr3d

array([[[64, 64, 64],
        [64, 64, 64]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [66]:
arr2d = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
arr_slice = arr2d[0]
arr_slice

array([0, 1, 2])

24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [67]:
arr2d = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
arr_slice = arr2d[1,1]
arr_slice

4

25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [70]:
arr2d = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
arr_slice = arr2d[0:2,2:]
arr_slice

array([[2],
       [5]])

26. Create a 10x10 array with random values and find the minimum and maximum values

In [77]:
arr1 = np.random.randn(10,10)  

# Given 10x10 random values can also be generated as: arr1 = np.random.random(100).reshape(10,10)

arr1, np.min(arr1), np.max(arr1)

(array([[-0.27242686, -0.31787222,  0.2689346 ,  0.03881329,  1.17151047,
          1.04377213,  0.27466654,  0.8817252 , -1.33648756,  1.51495117],
        [-1.36045543, -1.73532891, -0.39218388, -0.59526615,  1.14612874,
         -0.43710471,  0.66729366, -0.16064034,  0.28398887, -0.75015809],
        [-0.31452249, -0.62969541,  0.56631931,  1.23723442,  1.02642831,
         -0.56193153, -1.40170431, -0.1804835 , -0.23652315, -0.73346155],
        [ 0.36212524, -0.78152468, -0.89718219, -1.54494309, -0.52526174,
          0.90631287,  0.92463119,  0.19586936,  0.54152488,  1.32252623],
        [ 0.1659819 ,  0.02330639, -0.62340728,  0.25371266,  1.21748588,
         -2.67406052,  0.16038068, -0.06959315, -0.26908163,  0.68952075],
        [ 1.96247948, -1.03306192,  0.04150431,  0.41110655, -0.67102465,
          0.42070124,  0.6536378 , -0.28751931, -0.85348452,  1.0929529 ],
        [ 1.25123472, -1.30303762,  1.27619418, -0.73073142, -1.83381411,
         -0.49985641, -0.8541943

27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [29]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
c = np.intersect1d(a,b)
c

array([2, 4])

28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [80]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
res = np.flatnonzero(np.isin(a, b))
res

array([1, 3, 5, 7], dtype=int64)

29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [95]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
data, data[names != 'Will']

(array([[ 0.55724188, -0.74890786, -0.03578008, -0.74064656],
        [ 1.64231938,  1.12156919, -0.76195452, -0.80745386],
        [-0.13448645,  1.10067615,  1.01146199,  1.24302668],
        [-0.63824384,  1.13854327,  0.29751621, -0.43288407],
        [ 1.19506479,  1.52914891,  1.56643391,  0.55689984],
        [ 0.39297541,  0.40799061, -0.63860867,  0.99747777],
        [-0.33568449, -2.15676696,  0.52183507, -0.42152029]]),
 array([[ 0.55724188, -0.74890786, -0.03578008, -0.74064656],
        [ 1.64231938,  1.12156919, -0.76195452, -0.80745386],
        [-0.63824384,  1.13854327,  0.29751621, -0.43288407],
        [ 0.39297541,  0.40799061, -0.63860867,  0.99747777],
        [-0.33568449, -2.15676696,  0.52183507, -0.42152029]]))

30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [103]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)

# one way could be as: data[names == 'Bob']

data, data[(names != 'Will') & (names != 'Joe')]

(array([[-1.59451627, -0.45986037,  0.28393651,  0.70230871],
        [-0.29935527,  2.22442786, -0.2197125 , -0.87044405],
        [-0.83583367, -0.33000549,  0.49216195, -0.55970251],
        [-0.85972591,  2.2343142 , -0.23980983, -0.16403878],
        [-1.13918289, -1.28844066,  1.54914956,  0.86922247],
        [-0.55869743, -0.51793936, -0.28428821,  1.07343331],
        [ 0.42509555,  0.62485572, -0.09503883,  0.81546459]]),
 array([[-1.59451627, -0.45986037,  0.28393651,  0.70230871],
        [-0.85972591,  2.2343142 , -0.23980983, -0.16403878]]))

Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [34]:
arr = np.arange(1,16).reshape((5,3))
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [83]:
arr = np.arange(1,17).reshape((2,2,4))
arr

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

33. Swap axes of the array you created in Question 32

In [91]:
arr.swapaxes(1, 0)

array([[[ 1,  2,  3,  4],
        [ 9, 10, 11, 12]],

       [[ 5,  6,  7,  8],
        [13, 14, 15, 16]]])

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [79]:
arr = np.array([.1, 1, 0.2, 0, .5, .15, 12, 16, 9, 10])
#arr = np.sqrt(arr)
#arr[arr < 0.5] = 0
# above two statements would also work fine. Below statement is another way of doing the same.
arr = np.where(np.sqrt(arr) < 0.5, 0, np.sqrt(arr))
arr

array([0.        , 1.        , 0.        , 0.        , 0.70710678,
       0.        , 3.46410162, 4.        , 3.        , 3.16227766])

35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [84]:
arr1 = np.random.random(12)
arr2 = np.random.random(12)
#arr3 = np.where(arr1 > arr2, arr1, arr2) : This is another way of getting 3rd array with max values of first 2 arrays
arr3 = np.maximum(arr1,arr2)
# we can display all the three arrays and observe that 3rd array carries the max values of first 2 arrays
arr1, arr2, arr3

(array([0.28643844, 0.93874975, 0.850968  , 0.29949332, 0.82154677,
        0.63492583, 0.79989779, 0.97138052, 0.11703669, 0.37641679,
        0.81875889, 0.19378668]),
 array([0.90039855, 0.35630868, 0.39508484, 0.41433628, 0.19601372,
        0.88905299, 0.72305301, 0.68601064, 0.6124838 , 0.2425141 ,
        0.08745169, 0.28439296]),
 array([0.90039855, 0.93874975, 0.850968  , 0.41433628, 0.82154677,
        0.88905299, 0.79989779, 0.97138052, 0.6124838 , 0.37641679,
        0.81875889, 0.28439296]))

36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [92]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [108]:
a = np.array([1,2,3,4,5]) 
b = np.array([5,6,7,8,9])

np.setdiff1d(a,b) # another way could be as: a[~(np.isin(a,b))]


array([1, 2, 3, 4])

38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [124]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
newColumn = np.array([[10,10,10]])
sampleArray[:,1] = newColumn
sampleArray

array([[34, 10, 73],
       [82, 10, 12],
       [53, 10, 66]])

39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [113]:
x = np.array([[1., 2., 3.], [4., 5., 6.]]) 
y = np.array([[6., 23.], [-1, 7], [8, 9]])

x @ y  # We could also perfom dot matrix product as: np.dot(x,y)  Or  x.dot(y)


array([[ 28.,  64.],
       [ 67., 181.]])

40. Generate a matrix of 20 random values and find its cumulative sum

In [116]:
arr = np.random.random(20)
arr, arr.cumsum()

(array([0.65477816, 0.12369755, 0.43440882, 0.7524507 , 0.24843873,
        0.94883688, 0.30918073, 0.81716166, 0.54704431, 0.29492036,
        0.12252888, 0.67092711, 0.41042047, 0.14547949, 0.27726063,
        0.40961599, 0.11509962, 0.97102478, 0.77033815, 0.99774377]),
 array([ 0.65477816,  0.7784757 ,  1.21288452,  1.96533523,  2.21377395,
         3.16261083,  3.47179156,  4.28895322,  4.83599752,  5.13091788,
         5.25344676,  5.92437387,  6.33479434,  6.48027382,  6.75753445,
         7.16715044,  7.28225006,  8.25327484,  9.02361298, 10.02135676]))