# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [4]:
import numpy as np

2. Create a null vector of size 10 

In [5]:
Vector = np.zeros(10)
Vector

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3. Create a vector with values ranging from 10 to 49

In [6]:
A = np.arange(10,50)
print(A)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


4. Find the shape of previous array in question 3

In [11]:
A.shape

(40,)

5. Print the type of the previous array in question 3

In [12]:
A.dtype

dtype('int32')

6. Print the numpy version and the configuration


In [13]:
print(np.__version__, np.show_config())

blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['F:/AI/Conda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['F:/AI/Conda\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['F:/AI/Conda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['F:/AI/Conda\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['F:/AI/Conda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['F:/AI/Conda\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['F:/AI/Conda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['F:/AI/Conda\\Library\\include']
1.19.2 None


7. Print the dimension of the array in question 3


In [14]:
A.ndim

1

8. Create a boolean array with all the True values

In [34]:
arr = np.array(np.arange(10,50), dtype="bool")
print(arr)

[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True]


9. Create a two dimensional array




In [35]:
data2 = [[1,2,3,4,5],[1,2,3,4,5]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

10. Create a three dimensional array



In [38]:
data3 = [[[1,2,3,4,5],[1,2,3,4,5]],[[1,2,3,4,5],[1,2,3,4,5]]]
arr3 = np.array(data3)
arr3


array([[[1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5]],

       [[1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5]]])

Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [42]:
Arr3 = np.arange(1,10)
print(Arr3)
R_Arr3 = Arr3[::-1]
R_Arr3

[1 2 3 4 5 6 7 8 9]


array([9, 8, 7, 6, 5, 4, 3, 2, 1])

12. Create a null vector of size 10 but the fifth value which is 1 

In [45]:
null = np.zeros(10)
null[5] = 1
null



array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

13. Create a 3x3 identity matrix

In [47]:
I = np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [49]:
arr = np.array([1, 2, 3, 4, 5])
arr.dtype
arr.astype(np.float64)

array([1., 2., 3., 4., 5.])

15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [51]:
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]])  
arr2 = np.array([[0., 4., 1.],

           [7., 2., 12.]])
arr3 = arr1 * arr2
arr3

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [53]:
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]]) 
arr2 = np.array([[0., 4., 1.],

            [7., 2., 12.]])
arr3 = arr1 > arr2
arr3


array([[ True, False,  True],
       [False,  True, False]])

17. Extract all odd numbers from arr with values(0-9)

In [62]:
av = np.arange(10)
avo = av[av % 2 == 1]
print(avo)


[1 3 5 7 9]


18. Replace all odd numbers to -1 from previous array

In [65]:
av[av % 2 == 1] = -1
av

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [66]:
arr = np.arange(10)
arr[5:9] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

20. Create a 2d array with 1 on the border and 0 inside

In [73]:
c = np.ones([3,3])
c
c[1,1] = 0
c


array([[1., 1., 1.],
       [1., 0., 1.],
       [1., 1., 1.]])

Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [74]:
arr2d = np.array([[1, 2, 3],

            [4, 5, 6], 

            [7, 8, 9]])
arr2d[1,1] = 12
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [82]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[0,0] = 64
arr3d

array([[[64, 64, 64],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [106]:
v
fd = d2[0 , :5]
fd


[[0 1 2 3 4]
 [5 6 7 8 9]]


array([0, 1, 2, 3, 4])

24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [108]:
d2 = np.array([np.arange(5),np.arange(5,10)])
print(d2)
sl2 = d2[1,1]
sl2

[[0 1 2 3 4]
 [5 6 7 8 9]]


6

25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [114]:
d2 = np.array([np.arange(5),np.arange(5,10)])
print(d2)
sl2 = d2[:2, 2]
sl2

[[0 1 2 3 4]
 [5 6 7 8 9]]


array([2, 7])

26. Create a 10x10 array with random values and find the minimum and maximum values

In [130]:
ab = np.random.randn(10,10)
ab
min1 = np.amin(ab)
print(min1)
max1 = np.amax(ab)
max1

-3.7909178095730307


2.252788653525201

27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [134]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
c = np.intersect1d(a, b)
c

array([2, 4])

28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [135]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a == b)

(array([1, 3, 5, 7], dtype=int64),)

29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [143]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
print(names)
np.where(names != "Will")


['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']


(array([0, 1, 3, 5, 6], dtype=int64),)

30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [154]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
print(names)
np.where((names != "Will") & (names != "Joe"))

['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']


(array([0, 3], dtype=int64),)

Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [156]:
er = np.random.randn(15).reshape(5,3)
er

array([[ 0.83376121,  1.44015562,  1.31169509],
       [ 0.53920043, -0.50576571, -1.95456197],
       [ 0.82683209, -1.26557409, -0.22437074],
       [ 0.75620516,  0.29139104, -2.26022747],
       [ 0.31307991, -1.15146364, -0.25428749]])

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [157]:
er2 = np.random.randn(16).reshape(2,2,4)
er2

array([[[-0.22296686,  0.20039377,  1.84171743,  0.77059544],
        [ 0.7270712 ,  0.1321494 ,  0.76368872,  0.13728919]],

       [[ 2.02263312, -0.22028894,  1.71915079,  0.32758982],
        [-1.94403519,  0.24409702, -0.24479829, -0.27790798]]])

33. Swap axes of the array you created in Question 32

In [160]:
err3 = np.swapaxes(er2, 0, 1)
err3

array([[[-0.22296686,  0.20039377,  1.84171743,  0.77059544],
        [ 2.02263312, -0.22028894,  1.71915079,  0.32758982]],

       [[ 0.7270712 ,  0.1321494 ,  0.76368872,  0.13728919],
        [-1.94403519,  0.24409702, -0.24479829, -0.27790798]]])

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [165]:
bd = np.arange(10)
bds = np.sqrt(bd)
print(bds)
for a in bds:
    if a < 0.5:
        a = 0
bds

[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]


array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [186]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [189]:
a = np.array([1,2,3,4,5]) 
b = np.array([5,6,7,8,9])
np.intersect1d(a, b)


array([5])

38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [195]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
newColumn = np.array([[10,10,10]])
sampleArray[: , 1] = newColumn
sampleArray


array([[34, 10, 73],
       [82, 10, 12],
       [53, 10, 66]])

39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [185]:
x = np.array([[1., 2., 3.], [4., 5., 6.]]) 
y = np.array([[6., 23.], [-1, 7], [8, 9]])

print(np.dot(x, y))

[[ 28.  64.]
 [ 67. 181.]]


40. Generate a matrix of 20 random values and find its cumulative sum

In [183]:
asas = np.random.randn(20)
print(asas)
b = np.cumsum(asas)
b

[-0.01480176 -0.31327269  0.71819818  1.24482066  0.15371596 -1.78379471
 -1.37704138 -1.02417399 -0.04611254 -0.1043161  -1.41693372  0.40396893
 -0.14120239  1.42544299 -0.86785788  0.74660302 -0.16318099  0.90693839
 -2.18061579  0.67230067]


array([-0.01480176, -0.32807445,  0.39012373,  1.63494439,  1.78866035,
        0.00486564, -1.37217574, -2.39634972, -2.44246226, -2.54677836,
       -3.96371208, -3.55974315, -3.70094554, -2.27550255, -3.14336042,
       -2.39675741, -2.55993839, -1.653     , -3.83361579, -3.16131512])